services:
  database:
    container_name: database
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: booking
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - 5433:5432
    networks:
      backend:
        ipv4_address: 10.0.0.2
  api:
    container_name: api
    build:
      context: api
    restart: always
    depends_on:
     - 'database'
    env_file: api/.env
    ports:
      - 3000:8080
    networks:
      backend:
        ipv4_address: 10.0.0.3
      frontend:
  web:
    container_name: web
    build:
      context: web
    restart: always
    ports:
      - 8080:8080
    networks:
      backend:
        ipv4_address: 10.0.0.4
      frontend:

volumes:
  db-data:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1
  frontend:
    driver: bridge