version: "3.8"

services:
  database:
    container_name: database
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: booking
    volumes:
      - ./data/database:/var/lib/postgres/data
    ports:
      - "5432:5432"
    networks:
      backend:
        ipv4_address: 1.0.0.2
  api:
    container_name: api
    build:
      context: api
    restart: always
    depends_on:
     - database
    env_file: api/.env
    ports:
      - "81:8080"
    networks:
      backend:
        ipv4_address: 1.0.0.3
      frontend:
  web:
    container_name: web
    build:
      context: web
    restart: always
    ports:
      - "80:8080"
    networks:
      backend:
        ipv4_address: 1.0.0.4
      frontend:
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 1.0.0.0/29
          gateway: 1.0.0.1
  frontend:
    driver: bridge